columns:
  - LOCATION: category
  - PRICE: float64
  - LAND AREA: float64
  - ROAD ACCESS: float64
  - FACING: category
  - FLOOR: float64
  - BEDROOM: float64
  - BATHROOM: float64
  - PROPERTY AGE: float64
  - CITY: category

numerical_columns:
  - PRICE
  - LAND AREA
  - BEDROOM
  - BATHROOM
  - FLOOR
  - PROPERTY AGE
  - ROAD ACCESS

categorical_columns:
  - LOCATION
  - FACING

oe_columns:
  - FACING

ohe_columns:
  - LOCATION

power_transformer:
  - LAND AREA
  - BEDROOM
  - BATHROOM
  - FLOOR
  - PROPERTY AGE
  - ROAD ACCESS

si_num_columns:
  - ROAD ACCESS
  - FLOOR
  - BEDROOM
  - BATHROOM
  - CITY

si_cate_columns:
  - FACING
  - LOCATION


