columns:
  -PRICE : float64
  -LOCATION: category
  -LAND AREA: float64
  -FACING: category
  -ROAD ACESS: float64
  -BEDROOM: float64
  -BATHROOM: float64
  -PROPERTY AGE: float64
  -FLOOR: float64

numerical_columns:
  -PRICE
  -LAND AREA
  -BEDROOM
  -BATHROOM
  -FLOOR
  -PROPERY AGE
  -ROAD ACESS

categorical_columns:
  -LOCATION
  -FACING
  -LOCATION

replace_zero:
  -LAND AREA


oe_columns:
  -FACING

ohe_columns:
  -LOCATION

power_transformer:
  -LAND AREA
  -BEDROOM
  -BATHROOM
  -FLOOR
  -PROPERY AGE
  -ROAD ACESS

si_num_columns:
  -ROAD ACESS
  -FLOOR
  -BEDROOM
  -BATHROOM

si_cate_columns:
  -FACING

